# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.
from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.document_insights_response_200 import DocumentInsightsResponse200
from ...types import UNSET, File, Response, Unset


def _get_kwargs(
    *,
    body: File,
    file_name: str | Unset = "sample.pdf",
    pages_to_extract: str | Unset = "",
    tag: str | Unset = "default",
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
    use_webhook: str | Unset = "",
    webhook_metadata: str | Unset = "",
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    params: dict[str, Any] = {}

    params["file_name"] = file_name

    params["pages_to_extract"] = pages_to_extract

    params["tag"] = tag

    params["url"] = url_query

    params["url_in_post"] = url_in_post

    params["use_webhook"] = use_webhook

    params["webhook_metadata"] = webhook_metadata

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/api/v2/document-insights",
        "params": params,
    }

    _kwargs["content"] = body.payload
    headers["Content-Type"] = "application/octet-stream"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> DocumentInsightsResponse200 | None:
    if response.status_code == 200:
        response_200 = DocumentInsightsResponse200.from_dict(response.json())

        return response_200

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[DocumentInsightsResponse200]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: File,
    file_name: str | Unset = "sample.pdf",
    pages_to_extract: str | Unset = "",
    tag: str | Unset = "default",
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
    use_webhook: str | Unset = "",
    webhook_metadata: str | Unset = "",
) -> Response[DocumentInsightsResponse200]:
    """Run document insights over a file

    Args:
        file_name (str | Unset):  Default: 'sample.pdf'.
        pages_to_extract (str | Unset):  Default: ''.
        tag (str | Unset):  Default: 'default'.
        url_query (str | Unset):  Default: ''.
        url_in_post (bool | Unset):  Default: False.
        use_webhook (str | Unset):  Default: ''.
        webhook_metadata (str | Unset):  Default: ''.
        body (File):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[DocumentInsightsResponse200]
    """
    kwargs = _get_kwargs(
        body=body,
        file_name=file_name,
        pages_to_extract=pages_to_extract,
        tag=tag,
        url_query=url_query,
        url_in_post=url_in_post,
        use_webhook=use_webhook,
        webhook_metadata=webhook_metadata,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    body: File,
    file_name: str | Unset = "sample.pdf",
    pages_to_extract: str | Unset = "",
    tag: str | Unset = "default",
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
    use_webhook: str | Unset = "",
    webhook_metadata: str | Unset = "",
) -> DocumentInsightsResponse200 | None:
    """Run document insights over a file

    Args:
        file_name (str | Unset):  Default: 'sample.pdf'.
        pages_to_extract (str | Unset):  Default: ''.
        tag (str | Unset):  Default: 'default'.
        url_query (str | Unset):  Default: ''.
        url_in_post (bool | Unset):  Default: False.
        use_webhook (str | Unset):  Default: ''.
        webhook_metadata (str | Unset):  Default: ''.
        body (File):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        DocumentInsightsResponse200
    """
    return sync_detailed(
        client=client,
        body=body,
        file_name=file_name,
        pages_to_extract=pages_to_extract,
        tag=tag,
        url_query=url_query,
        url_in_post=url_in_post,
        use_webhook=use_webhook,
        webhook_metadata=webhook_metadata,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: File,
    file_name: str | Unset = "sample.pdf",
    pages_to_extract: str | Unset = "",
    tag: str | Unset = "default",
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
    use_webhook: str | Unset = "",
    webhook_metadata: str | Unset = "",
) -> Response[DocumentInsightsResponse200]:
    """Run document insights over a file

    Args:
        file_name (str | Unset):  Default: 'sample.pdf'.
        pages_to_extract (str | Unset):  Default: ''.
        tag (str | Unset):  Default: 'default'.
        url_query (str | Unset):  Default: ''.
        url_in_post (bool | Unset):  Default: False.
        use_webhook (str | Unset):  Default: ''.
        webhook_metadata (str | Unset):  Default: ''.
        body (File):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[DocumentInsightsResponse200]
    """
    kwargs = _get_kwargs(
        body=body,
        file_name=file_name,
        pages_to_extract=pages_to_extract,
        tag=tag,
        url_query=url_query,
        url_in_post=url_in_post,
        use_webhook=use_webhook,
        webhook_metadata=webhook_metadata,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    body: File,
    file_name: str | Unset = "sample.pdf",
    pages_to_extract: str | Unset = "",
    tag: str | Unset = "default",
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
    use_webhook: str | Unset = "",
    webhook_metadata: str | Unset = "",
) -> DocumentInsightsResponse200 | None:
    """Run document insights over a file

    Args:
        file_name (str | Unset):  Default: 'sample.pdf'.
        pages_to_extract (str | Unset):  Default: ''.
        tag (str | Unset):  Default: 'default'.
        url_query (str | Unset):  Default: ''.
        url_in_post (bool | Unset):  Default: False.
        use_webhook (str | Unset):  Default: ''.
        webhook_metadata (str | Unset):  Default: ''.
        body (File):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        DocumentInsightsResponse200
    """
    return (
        await asyncio_detailed(
            client=client,
            body=body,
            file_name=file_name,
            pages_to_extract=pages_to_extract,
            tag=tag,
            url_query=url_query,
            url_in_post=url_in_post,
            use_webhook=use_webhook,
            webhook_metadata=webhook_metadata,
        )
    ).parsed
