# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.
from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.whisper_accepted import WhisperAccepted
from ...types import UNSET, File, Response, Unset


def _get_kwargs(
    *,
    body: File | Unset = UNSET,
    file_name: str | Unset = "sample.pdf",
    mode: str | Unset = "form",
    pages_to_extract: str | Unset = UNSET,
    tag: str | Unset = "default",
    url_query: str | Unset = UNSET,
    url_in_post: bool | Unset = False,
    use_webhook: str | Unset = UNSET,
    webhook_metadata: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    params: dict[str, Any] = {}

    params["file_name"] = file_name

    params["mode"] = mode

    params["pages_to_extract"] = pages_to_extract

    params["tag"] = tag

    params["url"] = url_query

    params["url_in_post"] = url_in_post

    params["use_webhook"] = use_webhook

    params["webhook_metadata"] = webhook_metadata

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/api/v2/document-insights",
        "params": params,
    }

    if not isinstance(body, Unset):
        _kwargs["content"] = body.payload
    headers["Content-Type"] = "application/octet-stream"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | WhisperAccepted | None:
    if response.status_code == 202:
        response_202 = WhisperAccepted.from_dict(response.json())

        return response_202

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Error.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | WhisperAccepted]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: File | Unset = UNSET,
    file_name: str | Unset = "sample.pdf",
    mode: str | Unset = "form",
    pages_to_extract: str | Unset = UNSET,
    tag: str | Unset = "default",
    url_query: str | Unset = UNSET,
    url_in_post: bool | Unset = False,
    use_webhook: str | Unset = UNSET,
    webhook_metadata: str | Unset = UNSET,
) -> Response[Error | WhisperAccepted]:
    """Run document insights over a file

    Args:
        file_name (str | Unset):  Default: 'sample.pdf'.
        mode (str | Unset):  Default: 'form'.
        pages_to_extract (str | Unset):
        tag (str | Unset):  Default: 'default'.
        url_query (str | Unset):
        url_in_post (bool | Unset):  Default: False.
        use_webhook (str | Unset):
        webhook_metadata (str | Unset):
        body (File | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | WhisperAccepted]
    """
    kwargs = _get_kwargs(
        body=body,
        file_name=file_name,
        mode=mode,
        pages_to_extract=pages_to_extract,
        tag=tag,
        url_query=url_query,
        url_in_post=url_in_post,
        use_webhook=use_webhook,
        webhook_metadata=webhook_metadata,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    body: File | Unset = UNSET,
    file_name: str | Unset = "sample.pdf",
    mode: str | Unset = "form",
    pages_to_extract: str | Unset = UNSET,
    tag: str | Unset = "default",
    url_query: str | Unset = UNSET,
    url_in_post: bool | Unset = False,
    use_webhook: str | Unset = UNSET,
    webhook_metadata: str | Unset = UNSET,
) -> Error | WhisperAccepted | None:
    """Run document insights over a file

    Args:
        file_name (str | Unset):  Default: 'sample.pdf'.
        mode (str | Unset):  Default: 'form'.
        pages_to_extract (str | Unset):
        tag (str | Unset):  Default: 'default'.
        url_query (str | Unset):
        url_in_post (bool | Unset):  Default: False.
        use_webhook (str | Unset):
        webhook_metadata (str | Unset):
        body (File | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | WhisperAccepted
    """
    return sync_detailed(
        client=client,
        body=body,
        file_name=file_name,
        mode=mode,
        pages_to_extract=pages_to_extract,
        tag=tag,
        url_query=url_query,
        url_in_post=url_in_post,
        use_webhook=use_webhook,
        webhook_metadata=webhook_metadata,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: File | Unset = UNSET,
    file_name: str | Unset = "sample.pdf",
    mode: str | Unset = "form",
    pages_to_extract: str | Unset = UNSET,
    tag: str | Unset = "default",
    url_query: str | Unset = UNSET,
    url_in_post: bool | Unset = False,
    use_webhook: str | Unset = UNSET,
    webhook_metadata: str | Unset = UNSET,
) -> Response[Error | WhisperAccepted]:
    """Run document insights over a file

    Args:
        file_name (str | Unset):  Default: 'sample.pdf'.
        mode (str | Unset):  Default: 'form'.
        pages_to_extract (str | Unset):
        tag (str | Unset):  Default: 'default'.
        url_query (str | Unset):
        url_in_post (bool | Unset):  Default: False.
        use_webhook (str | Unset):
        webhook_metadata (str | Unset):
        body (File | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | WhisperAccepted]
    """
    kwargs = _get_kwargs(
        body=body,
        file_name=file_name,
        mode=mode,
        pages_to_extract=pages_to_extract,
        tag=tag,
        url_query=url_query,
        url_in_post=url_in_post,
        use_webhook=use_webhook,
        webhook_metadata=webhook_metadata,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    body: File | Unset = UNSET,
    file_name: str | Unset = "sample.pdf",
    mode: str | Unset = "form",
    pages_to_extract: str | Unset = UNSET,
    tag: str | Unset = "default",
    url_query: str | Unset = UNSET,
    url_in_post: bool | Unset = False,
    use_webhook: str | Unset = UNSET,
    webhook_metadata: str | Unset = UNSET,
) -> Error | WhisperAccepted | None:
    """Run document insights over a file

    Args:
        file_name (str | Unset):  Default: 'sample.pdf'.
        mode (str | Unset):  Default: 'form'.
        pages_to_extract (str | Unset):
        tag (str | Unset):  Default: 'default'.
        url_query (str | Unset):
        url_in_post (bool | Unset):  Default: False.
        use_webhook (str | Unset):
        webhook_metadata (str | Unset):
        body (File | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | WhisperAccepted
    """
    return (
        await asyncio_detailed(
            client=client,
            body=body,
            file_name=file_name,
            mode=mode,
            pages_to_extract=pages_to_extract,
            tag=tag,
            url_query=url_query,
            url_in_post=url_in_post,
            use_webhook=use_webhook,
            webhook_metadata=webhook_metadata,
        )
    ).parsed
