# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.
from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.webhook_delete_response_200 import WebhookDeleteResponse200
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    webhook_name: str | Unset = "",
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["webhook_name"] = webhook_name

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "delete",
        "url": "/api/v2/whisper-manage-callback",
        "params": params,
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> WebhookDeleteResponse200 | None:
    if response.status_code == 200:
        response_200 = WebhookDeleteResponse200.from_dict(response.json())

        return response_200

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[WebhookDeleteResponse200]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    webhook_name: str | Unset = "",
) -> Response[WebhookDeleteResponse200]:
    """Manage extraction webhooks

    Args:
        webhook_name (str | Unset):  Default: ''.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[WebhookDeleteResponse200]
    """
    kwargs = _get_kwargs(
        webhook_name=webhook_name,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    webhook_name: str | Unset = "",
) -> WebhookDeleteResponse200 | None:
    """Manage extraction webhooks

    Args:
        webhook_name (str | Unset):  Default: ''.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        WebhookDeleteResponse200
    """
    return sync_detailed(
        client=client,
        webhook_name=webhook_name,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    webhook_name: str | Unset = "",
) -> Response[WebhookDeleteResponse200]:
    """Manage extraction webhooks

    Args:
        webhook_name (str | Unset):  Default: ''.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[WebhookDeleteResponse200]
    """
    kwargs = _get_kwargs(
        webhook_name=webhook_name,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    webhook_name: str | Unset = "",
) -> WebhookDeleteResponse200 | None:
    """Manage extraction webhooks

    Args:
        webhook_name (str | Unset):  Default: ''.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        WebhookDeleteResponse200
    """
    return (
        await asyncio_detailed(
            client=client,
            webhook_name=webhook_name,
        )
    ).parsed
