# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.
from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.convert_xlsb_to_xlsx_response_200 import ConvertXlsbToXlsxResponse200
from ...types import UNSET, File, Response, Unset


def _get_kwargs(
    *,
    body: File,
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    params: dict[str, Any] = {}

    params["url"] = url_query

    params["url_in_post"] = url_in_post

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/api/v2/convert-xlsb-to-xlsx",
        "params": params,
    }

    _kwargs["content"] = body.payload
    headers["Content-Type"] = "application/octet-stream"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> ConvertXlsbToXlsxResponse200 | None:
    if response.status_code == 200:
        response_200 = ConvertXlsbToXlsxResponse200.from_dict(response.json())

        return response_200

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[ConvertXlsbToXlsxResponse200]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: File,
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
) -> Response[ConvertXlsbToXlsxResponse200]:
    """Convert an XLSB workbook to XLSX

    Args:
        url_query (str | Unset):  Default: ''.
        url_in_post (bool | Unset):  Default: False.
        body (File):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ConvertXlsbToXlsxResponse200]
    """
    kwargs = _get_kwargs(
        body=body,
        url_query=url_query,
        url_in_post=url_in_post,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    body: File,
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
) -> ConvertXlsbToXlsxResponse200 | None:
    """Convert an XLSB workbook to XLSX

    Args:
        url_query (str | Unset):  Default: ''.
        url_in_post (bool | Unset):  Default: False.
        body (File):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ConvertXlsbToXlsxResponse200
    """
    return sync_detailed(
        client=client,
        body=body,
        url_query=url_query,
        url_in_post=url_in_post,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: File,
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
) -> Response[ConvertXlsbToXlsxResponse200]:
    """Convert an XLSB workbook to XLSX

    Args:
        url_query (str | Unset):  Default: ''.
        url_in_post (bool | Unset):  Default: False.
        body (File):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ConvertXlsbToXlsxResponse200]
    """
    kwargs = _get_kwargs(
        body=body,
        url_query=url_query,
        url_in_post=url_in_post,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    body: File,
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
) -> ConvertXlsbToXlsxResponse200 | None:
    """Convert an XLSB workbook to XLSX

    Args:
        url_query (str | Unset):  Default: ''.
        url_in_post (bool | Unset):  Default: False.
        body (File):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ConvertXlsbToXlsxResponse200
    """
    return (
        await asyncio_detailed(
            client=client,
            body=body,
            url_query=url_query,
            url_in_post=url_in_post,
        )
    ).parsed
