# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.
from http import HTTPStatus
from io import BytesIO
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...types import UNSET, File, Response, Unset


def _get_kwargs(
    *,
    body: File | Unset = UNSET,
    url_query: str | Unset = UNSET,
    url_in_post: bool | Unset = False,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    params: dict[str, Any] = {}

    params["url"] = url_query

    params["url_in_post"] = url_in_post

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/api/v2/convert-to-pdf",
        "params": params,
    }

    if not isinstance(body, Unset):
        _kwargs["content"] = body.payload
    headers["Content-Type"] = "application/octet-stream"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Error | File | None:
    if response.status_code == 200:
        response_200 = File(payload=BytesIO(response.content))

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 402:
        response_402 = Error.from_dict(response.json())

        return response_402

    if response.status_code == 403:
        response_403 = Error.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 415:
        response_415 = Error.from_dict(response.json())

        return response_415

    if response.status_code == 500:
        response_500 = Error.from_dict(response.json())

        return response_500

    if response.status_code == 503:
        response_503 = Error.from_dict(response.json())

        return response_503

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[Error | File]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: File | Unset = UNSET,
    url_query: str | Unset = UNSET,
    url_in_post: bool | Unset = False,
) -> Response[Error | File]:
    """Convert a document to PDF

    Args:
        url_query (str | Unset):
        url_in_post (bool | Unset):  Default: False.
        body (File | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | File]
    """
    kwargs = _get_kwargs(
        body=body,
        url_query=url_query,
        url_in_post=url_in_post,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    body: File | Unset = UNSET,
    url_query: str | Unset = UNSET,
    url_in_post: bool | Unset = False,
) -> Error | File | None:
    """Convert a document to PDF

    Args:
        url_query (str | Unset):
        url_in_post (bool | Unset):  Default: False.
        body (File | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | File
    """
    return sync_detailed(
        client=client,
        body=body,
        url_query=url_query,
        url_in_post=url_in_post,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: File | Unset = UNSET,
    url_query: str | Unset = UNSET,
    url_in_post: bool | Unset = False,
) -> Response[Error | File]:
    """Convert a document to PDF

    Args:
        url_query (str | Unset):
        url_in_post (bool | Unset):  Default: False.
        body (File | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | File]
    """
    kwargs = _get_kwargs(
        body=body,
        url_query=url_query,
        url_in_post=url_in_post,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    body: File | Unset = UNSET,
    url_query: str | Unset = UNSET,
    url_in_post: bool | Unset = False,
) -> Error | File | None:
    """Convert a document to PDF

    Args:
        url_query (str | Unset):
        url_in_post (bool | Unset):  Default: False.
        body (File | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | File
    """
    return (
        await asyncio_detailed(
            client=client,
            body=body,
            url_query=url_query,
            url_in_post=url_in_post,
        )
    ).parsed
