# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.
from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.document_insights_retrieve_response_200 import DocumentInsightsRetrieveResponse200
from ...models.error import Error
from ...types import UNSET, Response


def _get_kwargs(
    *,
    whisper_hash: str,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["whisper_hash"] = whisper_hash

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/api/v2/document-insights-retrieve",
        "params": params,
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> DocumentInsightsRetrieveResponse200 | Error | None:
    if response.status_code == 200:
        response_200 = DocumentInsightsRetrieveResponse200.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 402:
        response_402 = Error.from_dict(response.json())

        return response_402

    if response.status_code == 403:
        response_403 = Error.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 415:
        response_415 = Error.from_dict(response.json())

        return response_415

    if response.status_code == 500:
        response_500 = Error.from_dict(response.json())

        return response_500

    if response.status_code == 503:
        response_503 = Error.from_dict(response.json())

        return response_503

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[DocumentInsightsRetrieveResponse200 | Error]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    whisper_hash: str,
) -> Response[DocumentInsightsRetrieveResponse200 | Error]:
    """Retrieve document insights result (destructive — one shot)

    Args:
        whisper_hash (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[DocumentInsightsRetrieveResponse200 | Error]
    """
    kwargs = _get_kwargs(
        whisper_hash=whisper_hash,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    whisper_hash: str,
) -> DocumentInsightsRetrieveResponse200 | Error | None:
    """Retrieve document insights result (destructive — one shot)

    Args:
        whisper_hash (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        DocumentInsightsRetrieveResponse200 | Error
    """
    return sync_detailed(
        client=client,
        whisper_hash=whisper_hash,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    whisper_hash: str,
) -> Response[DocumentInsightsRetrieveResponse200 | Error]:
    """Retrieve document insights result (destructive — one shot)

    Args:
        whisper_hash (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[DocumentInsightsRetrieveResponse200 | Error]
    """
    kwargs = _get_kwargs(
        whisper_hash=whisper_hash,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    whisper_hash: str,
) -> DocumentInsightsRetrieveResponse200 | Error | None:
    """Retrieve document insights result (destructive — one shot)

    Args:
        whisper_hash (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        DocumentInsightsRetrieveResponse200 | Error
    """
    return (
        await asyncio_detailed(
            client=client,
            whisper_hash=whisper_hash,
        )
    ).parsed
