# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.
from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.whisper_accepted import WhisperAccepted
from ...types import UNSET, File, Response, Unset


def _get_kwargs(
    *,
    body: File,
    add_line_nos: bool | Unset = False,
    allow_rotated_text: bool | Unset = True,
    checkbox_confidence_threshold: float | Unset = 0.3,
    derotate_threshold: float | Unset = 10.0,
    file_name: str | Unset = "sample.pdf",
    gaussian_blur_radius: float | Unset = 0.0,
    horizontal_stretch_factor: float | Unset = 1.0,
    ignore_vertical_text: bool | Unset = False,
    include_line_confidence: bool | Unset = False,
    lang: str | Unset = "eng",
    line_splitter_strategy: str | Unset = "left-priority",
    line_splitter_tolerance: float | Unset = 0.75,
    mark_horizontal_lines: bool | Unset = False,
    mark_vertical_lines: bool | Unset = False,
    median_filter_size: int | Unset = 0,
    min_table_width: float | Unset = 0.0,
    mode: str | Unset = "form",
    output_mode: str | Unset = "layout_preserving",
    page_separator: str | Unset = UNSET,
    pages_to_extract: str | Unset = "",
    tag: str | Unset = "default",
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
    use_webhook: str | Unset = "",
    watermark_angle_threshold: float | Unset = 25.0,
    webhook_metadata: str | Unset = "",
    word_confidence_threshold: float | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    params: dict[str, Any] = {}

    params["add_line_nos"] = add_line_nos

    params["allow_rotated_text"] = allow_rotated_text

    params["checkbox_confidence_threshold"] = checkbox_confidence_threshold

    params["derotate_threshold"] = derotate_threshold

    params["file_name"] = file_name

    params["gaussian_blur_radius"] = gaussian_blur_radius

    params["horizontal_stretch_factor"] = horizontal_stretch_factor

    params["ignore_vertical_text"] = ignore_vertical_text

    params["include_line_confidence"] = include_line_confidence

    params["lang"] = lang

    params["line_splitter_strategy"] = line_splitter_strategy

    params["line_splitter_tolerance"] = line_splitter_tolerance

    params["mark_horizontal_lines"] = mark_horizontal_lines

    params["mark_vertical_lines"] = mark_vertical_lines

    params["median_filter_size"] = median_filter_size

    params["min_table_width"] = min_table_width

    params["mode"] = mode

    params["output_mode"] = output_mode

    params["page_separator"] = page_separator

    params["pages_to_extract"] = pages_to_extract

    params["tag"] = tag

    params["url"] = url_query

    params["url_in_post"] = url_in_post

    params["use_webhook"] = use_webhook

    params["watermark_angle_threshold"] = watermark_angle_threshold

    params["webhook_metadata"] = webhook_metadata

    params["word_confidence_threshold"] = word_confidence_threshold

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/api/v2/whisper",
        "params": params,
    }

    _kwargs["content"] = body.payload
    headers["Content-Type"] = "application/octet-stream"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> WhisperAccepted | None:
    if response.status_code == 202:
        response_202 = WhisperAccepted.from_dict(response.json())

        return response_202

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[WhisperAccepted]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: File,
    add_line_nos: bool | Unset = False,
    allow_rotated_text: bool | Unset = True,
    checkbox_confidence_threshold: float | Unset = 0.3,
    derotate_threshold: float | Unset = 10.0,
    file_name: str | Unset = "sample.pdf",
    gaussian_blur_radius: float | Unset = 0.0,
    horizontal_stretch_factor: float | Unset = 1.0,
    ignore_vertical_text: bool | Unset = False,
    include_line_confidence: bool | Unset = False,
    lang: str | Unset = "eng",
    line_splitter_strategy: str | Unset = "left-priority",
    line_splitter_tolerance: float | Unset = 0.75,
    mark_horizontal_lines: bool | Unset = False,
    mark_vertical_lines: bool | Unset = False,
    median_filter_size: int | Unset = 0,
    min_table_width: float | Unset = 0.0,
    mode: str | Unset = "form",
    output_mode: str | Unset = "layout_preserving",
    page_separator: str | Unset = UNSET,
    pages_to_extract: str | Unset = "",
    tag: str | Unset = "default",
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
    use_webhook: str | Unset = "",
    watermark_angle_threshold: float | Unset = 25.0,
    webhook_metadata: str | Unset = "",
    word_confidence_threshold: float | Unset = UNSET,
) -> Response[WhisperAccepted]:
    """Submit a document for text extraction

    Args:
        add_line_nos (bool | Unset):  Default: False.
        allow_rotated_text (bool | Unset):  Default: True.
        checkbox_confidence_threshold (float | Unset):  Default: 0.3.
        derotate_threshold (float | Unset):  Default: 10.0.
        file_name (str | Unset):  Default: 'sample.pdf'.
        gaussian_blur_radius (float | Unset):  Default: 0.0.
        horizontal_stretch_factor (float | Unset):  Default: 1.0.
        ignore_vertical_text (bool | Unset):  Default: False.
        include_line_confidence (bool | Unset):  Default: False.
        lang (str | Unset):  Default: 'eng'.
        line_splitter_strategy (str | Unset):  Default: 'left-priority'.
        line_splitter_tolerance (float | Unset):  Default: 0.75.
        mark_horizontal_lines (bool | Unset):  Default: False.
        mark_vertical_lines (bool | Unset):  Default: False.
        median_filter_size (int | Unset):  Default: 0.
        min_table_width (float | Unset):  Default: 0.0.
        mode (str | Unset):  Default: 'form'.
        output_mode (str | Unset):  Default: 'layout_preserving'.
        page_separator (str | Unset):
        pages_to_extract (str | Unset):  Default: ''.
        tag (str | Unset):  Default: 'default'.
        url_query (str | Unset):  Default: ''.
        url_in_post (bool | Unset):  Default: False.
        use_webhook (str | Unset):  Default: ''.
        watermark_angle_threshold (float | Unset):  Default: 25.0.
        webhook_metadata (str | Unset):  Default: ''.
        word_confidence_threshold (float | Unset):
        body (File):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[WhisperAccepted]
    """
    kwargs = _get_kwargs(
        body=body,
        add_line_nos=add_line_nos,
        allow_rotated_text=allow_rotated_text,
        checkbox_confidence_threshold=checkbox_confidence_threshold,
        derotate_threshold=derotate_threshold,
        file_name=file_name,
        gaussian_blur_radius=gaussian_blur_radius,
        horizontal_stretch_factor=horizontal_stretch_factor,
        ignore_vertical_text=ignore_vertical_text,
        include_line_confidence=include_line_confidence,
        lang=lang,
        line_splitter_strategy=line_splitter_strategy,
        line_splitter_tolerance=line_splitter_tolerance,
        mark_horizontal_lines=mark_horizontal_lines,
        mark_vertical_lines=mark_vertical_lines,
        median_filter_size=median_filter_size,
        min_table_width=min_table_width,
        mode=mode,
        output_mode=output_mode,
        page_separator=page_separator,
        pages_to_extract=pages_to_extract,
        tag=tag,
        url_query=url_query,
        url_in_post=url_in_post,
        use_webhook=use_webhook,
        watermark_angle_threshold=watermark_angle_threshold,
        webhook_metadata=webhook_metadata,
        word_confidence_threshold=word_confidence_threshold,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    body: File,
    add_line_nos: bool | Unset = False,
    allow_rotated_text: bool | Unset = True,
    checkbox_confidence_threshold: float | Unset = 0.3,
    derotate_threshold: float | Unset = 10.0,
    file_name: str | Unset = "sample.pdf",
    gaussian_blur_radius: float | Unset = 0.0,
    horizontal_stretch_factor: float | Unset = 1.0,
    ignore_vertical_text: bool | Unset = False,
    include_line_confidence: bool | Unset = False,
    lang: str | Unset = "eng",
    line_splitter_strategy: str | Unset = "left-priority",
    line_splitter_tolerance: float | Unset = 0.75,
    mark_horizontal_lines: bool | Unset = False,
    mark_vertical_lines: bool | Unset = False,
    median_filter_size: int | Unset = 0,
    min_table_width: float | Unset = 0.0,
    mode: str | Unset = "form",
    output_mode: str | Unset = "layout_preserving",
    page_separator: str | Unset = UNSET,
    pages_to_extract: str | Unset = "",
    tag: str | Unset = "default",
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
    use_webhook: str | Unset = "",
    watermark_angle_threshold: float | Unset = 25.0,
    webhook_metadata: str | Unset = "",
    word_confidence_threshold: float | Unset = UNSET,
) -> WhisperAccepted | None:
    """Submit a document for text extraction

    Args:
        add_line_nos (bool | Unset):  Default: False.
        allow_rotated_text (bool | Unset):  Default: True.
        checkbox_confidence_threshold (float | Unset):  Default: 0.3.
        derotate_threshold (float | Unset):  Default: 10.0.
        file_name (str | Unset):  Default: 'sample.pdf'.
        gaussian_blur_radius (float | Unset):  Default: 0.0.
        horizontal_stretch_factor (float | Unset):  Default: 1.0.
        ignore_vertical_text (bool | Unset):  Default: False.
        include_line_confidence (bool | Unset):  Default: False.
        lang (str | Unset):  Default: 'eng'.
        line_splitter_strategy (str | Unset):  Default: 'left-priority'.
        line_splitter_tolerance (float | Unset):  Default: 0.75.
        mark_horizontal_lines (bool | Unset):  Default: False.
        mark_vertical_lines (bool | Unset):  Default: False.
        median_filter_size (int | Unset):  Default: 0.
        min_table_width (float | Unset):  Default: 0.0.
        mode (str | Unset):  Default: 'form'.
        output_mode (str | Unset):  Default: 'layout_preserving'.
        page_separator (str | Unset):
        pages_to_extract (str | Unset):  Default: ''.
        tag (str | Unset):  Default: 'default'.
        url_query (str | Unset):  Default: ''.
        url_in_post (bool | Unset):  Default: False.
        use_webhook (str | Unset):  Default: ''.
        watermark_angle_threshold (float | Unset):  Default: 25.0.
        webhook_metadata (str | Unset):  Default: ''.
        word_confidence_threshold (float | Unset):
        body (File):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        WhisperAccepted
    """
    return sync_detailed(
        client=client,
        body=body,
        add_line_nos=add_line_nos,
        allow_rotated_text=allow_rotated_text,
        checkbox_confidence_threshold=checkbox_confidence_threshold,
        derotate_threshold=derotate_threshold,
        file_name=file_name,
        gaussian_blur_radius=gaussian_blur_radius,
        horizontal_stretch_factor=horizontal_stretch_factor,
        ignore_vertical_text=ignore_vertical_text,
        include_line_confidence=include_line_confidence,
        lang=lang,
        line_splitter_strategy=line_splitter_strategy,
        line_splitter_tolerance=line_splitter_tolerance,
        mark_horizontal_lines=mark_horizontal_lines,
        mark_vertical_lines=mark_vertical_lines,
        median_filter_size=median_filter_size,
        min_table_width=min_table_width,
        mode=mode,
        output_mode=output_mode,
        page_separator=page_separator,
        pages_to_extract=pages_to_extract,
        tag=tag,
        url_query=url_query,
        url_in_post=url_in_post,
        use_webhook=use_webhook,
        watermark_angle_threshold=watermark_angle_threshold,
        webhook_metadata=webhook_metadata,
        word_confidence_threshold=word_confidence_threshold,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: File,
    add_line_nos: bool | Unset = False,
    allow_rotated_text: bool | Unset = True,
    checkbox_confidence_threshold: float | Unset = 0.3,
    derotate_threshold: float | Unset = 10.0,
    file_name: str | Unset = "sample.pdf",
    gaussian_blur_radius: float | Unset = 0.0,
    horizontal_stretch_factor: float | Unset = 1.0,
    ignore_vertical_text: bool | Unset = False,
    include_line_confidence: bool | Unset = False,
    lang: str | Unset = "eng",
    line_splitter_strategy: str | Unset = "left-priority",
    line_splitter_tolerance: float | Unset = 0.75,
    mark_horizontal_lines: bool | Unset = False,
    mark_vertical_lines: bool | Unset = False,
    median_filter_size: int | Unset = 0,
    min_table_width: float | Unset = 0.0,
    mode: str | Unset = "form",
    output_mode: str | Unset = "layout_preserving",
    page_separator: str | Unset = UNSET,
    pages_to_extract: str | Unset = "",
    tag: str | Unset = "default",
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
    use_webhook: str | Unset = "",
    watermark_angle_threshold: float | Unset = 25.0,
    webhook_metadata: str | Unset = "",
    word_confidence_threshold: float | Unset = UNSET,
) -> Response[WhisperAccepted]:
    """Submit a document for text extraction

    Args:
        add_line_nos (bool | Unset):  Default: False.
        allow_rotated_text (bool | Unset):  Default: True.
        checkbox_confidence_threshold (float | Unset):  Default: 0.3.
        derotate_threshold (float | Unset):  Default: 10.0.
        file_name (str | Unset):  Default: 'sample.pdf'.
        gaussian_blur_radius (float | Unset):  Default: 0.0.
        horizontal_stretch_factor (float | Unset):  Default: 1.0.
        ignore_vertical_text (bool | Unset):  Default: False.
        include_line_confidence (bool | Unset):  Default: False.
        lang (str | Unset):  Default: 'eng'.
        line_splitter_strategy (str | Unset):  Default: 'left-priority'.
        line_splitter_tolerance (float | Unset):  Default: 0.75.
        mark_horizontal_lines (bool | Unset):  Default: False.
        mark_vertical_lines (bool | Unset):  Default: False.
        median_filter_size (int | Unset):  Default: 0.
        min_table_width (float | Unset):  Default: 0.0.
        mode (str | Unset):  Default: 'form'.
        output_mode (str | Unset):  Default: 'layout_preserving'.
        page_separator (str | Unset):
        pages_to_extract (str | Unset):  Default: ''.
        tag (str | Unset):  Default: 'default'.
        url_query (str | Unset):  Default: ''.
        url_in_post (bool | Unset):  Default: False.
        use_webhook (str | Unset):  Default: ''.
        watermark_angle_threshold (float | Unset):  Default: 25.0.
        webhook_metadata (str | Unset):  Default: ''.
        word_confidence_threshold (float | Unset):
        body (File):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[WhisperAccepted]
    """
    kwargs = _get_kwargs(
        body=body,
        add_line_nos=add_line_nos,
        allow_rotated_text=allow_rotated_text,
        checkbox_confidence_threshold=checkbox_confidence_threshold,
        derotate_threshold=derotate_threshold,
        file_name=file_name,
        gaussian_blur_radius=gaussian_blur_radius,
        horizontal_stretch_factor=horizontal_stretch_factor,
        ignore_vertical_text=ignore_vertical_text,
        include_line_confidence=include_line_confidence,
        lang=lang,
        line_splitter_strategy=line_splitter_strategy,
        line_splitter_tolerance=line_splitter_tolerance,
        mark_horizontal_lines=mark_horizontal_lines,
        mark_vertical_lines=mark_vertical_lines,
        median_filter_size=median_filter_size,
        min_table_width=min_table_width,
        mode=mode,
        output_mode=output_mode,
        page_separator=page_separator,
        pages_to_extract=pages_to_extract,
        tag=tag,
        url_query=url_query,
        url_in_post=url_in_post,
        use_webhook=use_webhook,
        watermark_angle_threshold=watermark_angle_threshold,
        webhook_metadata=webhook_metadata,
        word_confidence_threshold=word_confidence_threshold,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    body: File,
    add_line_nos: bool | Unset = False,
    allow_rotated_text: bool | Unset = True,
    checkbox_confidence_threshold: float | Unset = 0.3,
    derotate_threshold: float | Unset = 10.0,
    file_name: str | Unset = "sample.pdf",
    gaussian_blur_radius: float | Unset = 0.0,
    horizontal_stretch_factor: float | Unset = 1.0,
    ignore_vertical_text: bool | Unset = False,
    include_line_confidence: bool | Unset = False,
    lang: str | Unset = "eng",
    line_splitter_strategy: str | Unset = "left-priority",
    line_splitter_tolerance: float | Unset = 0.75,
    mark_horizontal_lines: bool | Unset = False,
    mark_vertical_lines: bool | Unset = False,
    median_filter_size: int | Unset = 0,
    min_table_width: float | Unset = 0.0,
    mode: str | Unset = "form",
    output_mode: str | Unset = "layout_preserving",
    page_separator: str | Unset = UNSET,
    pages_to_extract: str | Unset = "",
    tag: str | Unset = "default",
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
    use_webhook: str | Unset = "",
    watermark_angle_threshold: float | Unset = 25.0,
    webhook_metadata: str | Unset = "",
    word_confidence_threshold: float | Unset = UNSET,
) -> WhisperAccepted | None:
    """Submit a document for text extraction

    Args:
        add_line_nos (bool | Unset):  Default: False.
        allow_rotated_text (bool | Unset):  Default: True.
        checkbox_confidence_threshold (float | Unset):  Default: 0.3.
        derotate_threshold (float | Unset):  Default: 10.0.
        file_name (str | Unset):  Default: 'sample.pdf'.
        gaussian_blur_radius (float | Unset):  Default: 0.0.
        horizontal_stretch_factor (float | Unset):  Default: 1.0.
        ignore_vertical_text (bool | Unset):  Default: False.
        include_line_confidence (bool | Unset):  Default: False.
        lang (str | Unset):  Default: 'eng'.
        line_splitter_strategy (str | Unset):  Default: 'left-priority'.
        line_splitter_tolerance (float | Unset):  Default: 0.75.
        mark_horizontal_lines (bool | Unset):  Default: False.
        mark_vertical_lines (bool | Unset):  Default: False.
        median_filter_size (int | Unset):  Default: 0.
        min_table_width (float | Unset):  Default: 0.0.
        mode (str | Unset):  Default: 'form'.
        output_mode (str | Unset):  Default: 'layout_preserving'.
        page_separator (str | Unset):
        pages_to_extract (str | Unset):  Default: ''.
        tag (str | Unset):  Default: 'default'.
        url_query (str | Unset):  Default: ''.
        url_in_post (bool | Unset):  Default: False.
        use_webhook (str | Unset):  Default: ''.
        watermark_angle_threshold (float | Unset):  Default: 25.0.
        webhook_metadata (str | Unset):  Default: ''.
        word_confidence_threshold (float | Unset):
        body (File):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        WhisperAccepted
    """
    return (
        await asyncio_detailed(
            client=client,
            body=body,
            add_line_nos=add_line_nos,
            allow_rotated_text=allow_rotated_text,
            checkbox_confidence_threshold=checkbox_confidence_threshold,
            derotate_threshold=derotate_threshold,
            file_name=file_name,
            gaussian_blur_radius=gaussian_blur_radius,
            horizontal_stretch_factor=horizontal_stretch_factor,
            ignore_vertical_text=ignore_vertical_text,
            include_line_confidence=include_line_confidence,
            lang=lang,
            line_splitter_strategy=line_splitter_strategy,
            line_splitter_tolerance=line_splitter_tolerance,
            mark_horizontal_lines=mark_horizontal_lines,
            mark_vertical_lines=mark_vertical_lines,
            median_filter_size=median_filter_size,
            min_table_width=min_table_width,
            mode=mode,
            output_mode=output_mode,
            page_separator=page_separator,
            pages_to_extract=pages_to_extract,
            tag=tag,
            url_query=url_query,
            url_in_post=url_in_post,
            use_webhook=use_webhook,
            watermark_angle_threshold=watermark_angle_threshold,
            webhook_metadata=webhook_metadata,
            word_confidence_threshold=word_confidence_threshold,
        )
    ).parsed
