# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.
from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.highlights_response_200 import HighlightsResponse200
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    extract_all_lines: str | Unset = "false",
    lines: str | Unset = "",
    whisper_hash: str | Unset = "",
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["extract_all_lines"] = extract_all_lines

    params["lines"] = lines

    params["whisper_hash"] = whisper_hash

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/api/v2/highlights",
        "params": params,
    }

    return _kwargs


def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> HighlightsResponse200 | None:
    if response.status_code == 200:
        response_200 = HighlightsResponse200.from_dict(response.json())

        return response_200

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[HighlightsResponse200]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    extract_all_lines: str | Unset = "false",
    lines: str | Unset = "",
    whisper_hash: str | Unset = "",
) -> Response[HighlightsResponse200]:
    """Line-level highlight geometry for an extraction

    Args:
        extract_all_lines (str | Unset):  Default: 'false'.
        lines (str | Unset):  Default: ''.
        whisper_hash (str | Unset):  Default: ''.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[HighlightsResponse200]
    """
    kwargs = _get_kwargs(
        extract_all_lines=extract_all_lines,
        lines=lines,
        whisper_hash=whisper_hash,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    extract_all_lines: str | Unset = "false",
    lines: str | Unset = "",
    whisper_hash: str | Unset = "",
) -> HighlightsResponse200 | None:
    """Line-level highlight geometry for an extraction

    Args:
        extract_all_lines (str | Unset):  Default: 'false'.
        lines (str | Unset):  Default: ''.
        whisper_hash (str | Unset):  Default: ''.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        HighlightsResponse200
    """
    return sync_detailed(
        client=client,
        extract_all_lines=extract_all_lines,
        lines=lines,
        whisper_hash=whisper_hash,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    extract_all_lines: str | Unset = "false",
    lines: str | Unset = "",
    whisper_hash: str | Unset = "",
) -> Response[HighlightsResponse200]:
    """Line-level highlight geometry for an extraction

    Args:
        extract_all_lines (str | Unset):  Default: 'false'.
        lines (str | Unset):  Default: ''.
        whisper_hash (str | Unset):  Default: ''.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[HighlightsResponse200]
    """
    kwargs = _get_kwargs(
        extract_all_lines=extract_all_lines,
        lines=lines,
        whisper_hash=whisper_hash,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    extract_all_lines: str | Unset = "false",
    lines: str | Unset = "",
    whisper_hash: str | Unset = "",
) -> HighlightsResponse200 | None:
    """Line-level highlight geometry for an extraction

    Args:
        extract_all_lines (str | Unset):  Default: 'false'.
        lines (str | Unset):  Default: ''.
        whisper_hash (str | Unset):  Default: ''.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        HighlightsResponse200
    """
    return (
        await asyncio_detailed(
            client=client,
            extract_all_lines=extract_all_lines,
            lines=lines,
            whisper_hash=whisper_hash,
        )
    ).parsed
