# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.
from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.pdf_to_images_response_200 import PdfToImagesResponse200
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    file_name: str | Unset = "sample.pdf",
    format_: str | Unset = "png",
    tag: str | Unset = "default",
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["file_name"] = file_name

    params["format"] = format_

    params["tag"] = tag

    params["url"] = url_query

    params["url_in_post"] = url_in_post

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/api/v2/pdf-to-images",
        "params": params,
    }

    return _kwargs


def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> PdfToImagesResponse200 | None:
    if response.status_code == 200:
        response_200 = PdfToImagesResponse200.from_dict(response.json())

        return response_200

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[PdfToImagesResponse200]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    file_name: str | Unset = "sample.pdf",
    format_: str | Unset = "png",
    tag: str | Unset = "default",
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
) -> Response[PdfToImagesResponse200]:
    """Pdf to images

    Args:
        file_name (str | Unset):  Default: 'sample.pdf'.
        format_ (str | Unset):  Default: 'png'.
        tag (str | Unset):  Default: 'default'.
        url_query (str | Unset):  Default: ''.
        url_in_post (bool | Unset):  Default: False.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[PdfToImagesResponse200]
    """
    kwargs = _get_kwargs(
        file_name=file_name,
        format_=format_,
        tag=tag,
        url_query=url_query,
        url_in_post=url_in_post,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    file_name: str | Unset = "sample.pdf",
    format_: str | Unset = "png",
    tag: str | Unset = "default",
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
) -> PdfToImagesResponse200 | None:
    """Pdf to images

    Args:
        file_name (str | Unset):  Default: 'sample.pdf'.
        format_ (str | Unset):  Default: 'png'.
        tag (str | Unset):  Default: 'default'.
        url_query (str | Unset):  Default: ''.
        url_in_post (bool | Unset):  Default: False.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        PdfToImagesResponse200
    """
    return sync_detailed(
        client=client,
        file_name=file_name,
        format_=format_,
        tag=tag,
        url_query=url_query,
        url_in_post=url_in_post,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    file_name: str | Unset = "sample.pdf",
    format_: str | Unset = "png",
    tag: str | Unset = "default",
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
) -> Response[PdfToImagesResponse200]:
    """Pdf to images

    Args:
        file_name (str | Unset):  Default: 'sample.pdf'.
        format_ (str | Unset):  Default: 'png'.
        tag (str | Unset):  Default: 'default'.
        url_query (str | Unset):  Default: ''.
        url_in_post (bool | Unset):  Default: False.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[PdfToImagesResponse200]
    """
    kwargs = _get_kwargs(
        file_name=file_name,
        format_=format_,
        tag=tag,
        url_query=url_query,
        url_in_post=url_in_post,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    file_name: str | Unset = "sample.pdf",
    format_: str | Unset = "png",
    tag: str | Unset = "default",
    url_query: str | Unset = "",
    url_in_post: bool | Unset = False,
) -> PdfToImagesResponse200 | None:
    """Pdf to images

    Args:
        file_name (str | Unset):  Default: 'sample.pdf'.
        format_ (str | Unset):  Default: 'png'.
        tag (str | Unset):  Default: 'default'.
        url_query (str | Unset):  Default: ''.
        url_in_post (bool | Unset):  Default: False.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        PdfToImagesResponse200
    """
    return (
        await asyncio_detailed(
            client=client,
            file_name=file_name,
            format_=format_,
            tag=tag,
            url_query=url_query,
            url_in_post=url_in_post,
        )
    ).parsed
