# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.
from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.whisper_result import WhisperResult
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    text_only: bool | Unset = False,
    whisper_hash: str,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["text_only"] = text_only

    params["whisper_hash"] = whisper_hash

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/api/v2/whisper-retrieve",
        "params": params,
    }

    return _kwargs


def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Error | WhisperResult | None:
    if response.status_code == 200:
        response_200 = WhisperResult.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Error.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | WhisperResult]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    text_only: bool | Unset = False,
    whisper_hash: str,
) -> Response[Error | WhisperResult]:
    """Retrieve extraction result (destructive — one shot)

    Args:
        text_only (bool | Unset):  Default: False.
        whisper_hash (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | WhisperResult]
    """
    kwargs = _get_kwargs(
        text_only=text_only,
        whisper_hash=whisper_hash,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    text_only: bool | Unset = False,
    whisper_hash: str,
) -> Error | WhisperResult | None:
    """Retrieve extraction result (destructive — one shot)

    Args:
        text_only (bool | Unset):  Default: False.
        whisper_hash (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | WhisperResult
    """
    return sync_detailed(
        client=client,
        text_only=text_only,
        whisper_hash=whisper_hash,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    text_only: bool | Unset = False,
    whisper_hash: str,
) -> Response[Error | WhisperResult]:
    """Retrieve extraction result (destructive — one shot)

    Args:
        text_only (bool | Unset):  Default: False.
        whisper_hash (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | WhisperResult]
    """
    kwargs = _get_kwargs(
        text_only=text_only,
        whisper_hash=whisper_hash,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    text_only: bool | Unset = False,
    whisper_hash: str,
) -> Error | WhisperResult | None:
    """Retrieve extraction result (destructive — one shot)

    Args:
        text_only (bool | Unset):  Default: False.
        whisper_hash (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | WhisperResult
    """
    return (
        await asyncio_detailed(
            client=client,
            text_only=text_only,
            whisper_hash=whisper_hash,
        )
    ).parsed
