# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.
from typing import Literal

ExtractLineSplitterStrategy = Literal["left-priority", "mid-priority", "right-priority"]

EXTRACT_LINE_SPLITTER_STRATEGY_VALUES: set[ExtractLineSplitterStrategy] = {
    "left-priority",
    "mid-priority",
    "right-priority",
}


def check_extract_line_splitter_strategy(value: str) -> ExtractLineSplitterStrategy:
    if value in EXTRACT_LINE_SPLITTER_STRATEGY_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {EXTRACT_LINE_SPLITTER_STRATEGY_VALUES!r}")
