# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.
from typing import Literal

ExtractOutputMode = Literal["layout_preserving", "text"]

EXTRACT_OUTPUT_MODE_VALUES: set[ExtractOutputMode] = {
    "layout_preserving",
    "text",
}


def check_extract_output_mode(value: str) -> ExtractOutputMode:
    if value in EXTRACT_OUTPUT_MODE_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {EXTRACT_OUTPUT_MODE_VALUES!r}")
