# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.
from typing import Literal

ExtractMode = Literal["document_insights", "excel", "form", "high_quality", "low_cost", "native_text", "table"]

EXTRACT_MODE_VALUES: set[ExtractMode] = {
    "document_insights",
    "excel",
    "form",
    "high_quality",
    "low_cost",
    "native_text",
    "table",
}


def check_extract_mode(value: str) -> ExtractMode:
    if value in EXTRACT_MODE_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {EXTRACT_MODE_VALUES!r}")
