# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.
from typing import Literal

PdfToImagesFormat = Literal["jpeg", "png"]

PDF_TO_IMAGES_FORMAT_VALUES: set[PdfToImagesFormat] = {
    "jpeg",
    "png",
}


def check_pdf_to_images_format(value: str) -> PdfToImagesFormat:
    if value in PDF_TO_IMAGES_FORMAT_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {PDF_TO_IMAGES_FORMAT_VALUES!r}")
