# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Self, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

T = TypeVar("T", bound="WebhookConfig")


@_attrs_define
class WebhookConfig:
    """
    Attributes:
        auth_token (str):
        url (str):
        webhook_name (str):
    """

    auth_token: str
    url: str
    webhook_name: str
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        auth_token = self.auth_token

        url = self.url

        webhook_name = self.webhook_name

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "auth_token": auth_token,
                "url": url,
                "webhook_name": webhook_name,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> Self:
        d = dict(src_dict)
        auth_token = d.pop("auth_token")

        url = d.pop("url")

        webhook_name = d.pop("webhook_name")

        webhook_config = cls(
            auth_token=auth_token,
            url=url,
            webhook_name=webhook_name,
        )

        webhook_config.additional_properties = d
        return webhook_config

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
