# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Self, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="WhisperAccepted")


@_attrs_define
class WhisperAccepted:
    """
    Attributes:
        format_ (str | Unset):
        message (str | Unset):
        status (str | Unset):
        whisper_hash (str | Unset):
    """

    format_: str | Unset = UNSET
    message: str | Unset = UNSET
    status: str | Unset = UNSET
    whisper_hash: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        format_ = self.format_

        message = self.message

        status = self.status

        whisper_hash = self.whisper_hash

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if format_ is not UNSET:
            field_dict["format"] = format_
        if message is not UNSET:
            field_dict["message"] = message
        if status is not UNSET:
            field_dict["status"] = status
        if whisper_hash is not UNSET:
            field_dict["whisper_hash"] = whisper_hash

        return field_dict

    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> Self:
        d = dict(src_dict)
        format_ = d.pop("format", UNSET)

        message = d.pop("message", UNSET)

        status = d.pop("status", UNSET)

        whisper_hash = d.pop("whisper_hash", UNSET)

        whisper_accepted = cls(
            format_=format_,
            message=message,
            status=status,
            whisper_hash=whisper_hash,
        )

        whisper_accepted.additional_properties = d
        return whisper_accepted

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
