# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.
from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.highlights_response_200 import HighlightsResponse200
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    extract_all_lines: bool | Unset = False,
    lines: str | Unset = UNSET,
    whisper_hash: str,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["extract_all_lines"] = extract_all_lines

    params["lines"] = lines

    params["whisper_hash"] = whisper_hash

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/api/v2/highlights",
        "params": params,
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | HighlightsResponse200 | None:
    if response.status_code == 200:
        response_200 = HighlightsResponse200.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 402:
        response_402 = Error.from_dict(response.json())

        return response_402

    if response.status_code == 403:
        response_403 = Error.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 415:
        response_415 = Error.from_dict(response.json())

        return response_415

    if response.status_code == 500:
        response_500 = Error.from_dict(response.json())

        return response_500

    if response.status_code == 503:
        response_503 = Error.from_dict(response.json())

        return response_503

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | HighlightsResponse200]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    extract_all_lines: bool | Unset = False,
    lines: str | Unset = UNSET,
    whisper_hash: str,
) -> Response[Error | HighlightsResponse200]:
    """Line-level highlight geometry for an extraction

    Args:
        extract_all_lines (bool | Unset):  Default: False.
        lines (str | Unset):
        whisper_hash (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | HighlightsResponse200]
    """
    kwargs = _get_kwargs(
        extract_all_lines=extract_all_lines,
        lines=lines,
        whisper_hash=whisper_hash,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    extract_all_lines: bool | Unset = False,
    lines: str | Unset = UNSET,
    whisper_hash: str,
) -> Error | HighlightsResponse200 | None:
    """Line-level highlight geometry for an extraction

    Args:
        extract_all_lines (bool | Unset):  Default: False.
        lines (str | Unset):
        whisper_hash (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | HighlightsResponse200
    """
    return sync_detailed(
        client=client,
        extract_all_lines=extract_all_lines,
        lines=lines,
        whisper_hash=whisper_hash,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    extract_all_lines: bool | Unset = False,
    lines: str | Unset = UNSET,
    whisper_hash: str,
) -> Response[Error | HighlightsResponse200]:
    """Line-level highlight geometry for an extraction

    Args:
        extract_all_lines (bool | Unset):  Default: False.
        lines (str | Unset):
        whisper_hash (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | HighlightsResponse200]
    """
    kwargs = _get_kwargs(
        extract_all_lines=extract_all_lines,
        lines=lines,
        whisper_hash=whisper_hash,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    extract_all_lines: bool | Unset = False,
    lines: str | Unset = UNSET,
    whisper_hash: str,
) -> Error | HighlightsResponse200 | None:
    """Line-level highlight geometry for an extraction

    Args:
        extract_all_lines (bool | Unset):  Default: False.
        lines (str | Unset):
        whisper_hash (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | HighlightsResponse200
    """
    return (
        await asyncio_detailed(
            client=client,
            extract_all_lines=extract_all_lines,
            lines=lines,
            whisper_hash=whisper_hash,
        )
    ).parsed
