#!/usr/bin/env bash
# Regenerate the transport layer from the committed OpenAPI spec.
#
# The generated tree is committed but NEVER hand-edited: regeneration overwrites
# it wholesale, so a fix applied there is lost on the next run. Fixes belong in
# the facade (client_v2.py) or upstream in the spec.
#
#   ./tools/gen_sdk.sh && git diff --stat src/unstract/llmwhisperer/sdk_llmwhisperer
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Where specs/llmwhisperer.json came from. It is a copy, not a fork: refresh it
# by re-copying from upstream at a newer revision and recording that revision
# here, so the next refresher can tell what they are replacing.
SPEC_SOURCE_REPO="Zipstack/unstract-llm-whisperer"
SPEC_SOURCE_PATH="specs/llmwhisperer.json"
SPEC_SOURCE_REV="750f941ee229e12cc05d8bd85edaab6a337a8758"

VENV="$REPO/.gen-venv"
# The generator shells out to ruff for its own post-processing. Without this it
# finds whatever ruff the caller happens to have, or none, and reports the miss
# as a warning -- which the gate below reads as an unparsable spec.
export PATH="$VENV/bin:$PATH"
OUT="src/unstract/llmwhisperer/sdk_llmwhisperer"
# Pinned: unpinned, a generator upgrade and a spec change produce the same diff,
# and the drift gate can no longer tell them apart.
GENERATOR="openapi-python-client==0.29.0"

if [ ! -x "$VENV/bin/openapi-python-client" ]; then
  uv venv "$VENV"
  uv pip install --python "$VENV/bin/python" "$GENERATOR"
fi

want="${GENERATOR#*==}"
have="$("$VENV/bin/openapi-python-client" --version | awk '{print $NF}')"
if [ "$have" != "$want" ]; then
  echo "generator is $have, expected $want — reinstalling" >&2
  uv pip install --python "$VENV/bin/python" "$GENERATOR"
fi

rm -rf "${REPO:?}/$OUT"
log="$(mktemp)"
trap 'rm -f "$log"' EXIT
(cd "$REPO" && "$VENV/bin/openapi-python-client" generate \
    --path "$REPO/specs/llmwhisperer.json" --output-path "$REPO/$OUT" \
    --config "$REPO/tools/openapi-client.yaml" --overwrite --meta none) 2>&1 | tee "$log"

# The generator downgrades a schema it cannot parse to a warning, drops
# the endpoint or model it belongs to, writes the rest and exits 0. The
# result is a client missing an operation and a spec that still looks fine.
if grep -qi warning "$log"; then
  echo "the generator reported a problem above and still exited 0; whatever it could not parse is missing from the output" >&2
  exit 1
fi

# Stamp every file, so the rule survives contact with a reader who arrived via
# grep rather than via this script.
header='# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.'
find "$REPO/$OUT" -name '*.py' -print0 | while IFS= read -r -d '' f; do
  printf '%s\n%s\n' "$header" "$(cat "$f")" > "$f.tmp" && mv "$f.tmp" "$f"
done

echo "generated $OUT ($(find "$REPO/$OUT" -name '*.py' | wc -l) files)"
echo "from $SPEC_SOURCE_REPO $SPEC_SOURCE_PATH @ $SPEC_SOURCE_REV"
