# Generated by tools/gen_sdk.sh from specs/llmwhisperer.json. DO NOT EDIT.
"""A client library for accessing Unstract LLMWhisperer"""

from .client import AuthenticatedClient, Client

__all__ = (
    "AuthenticatedClient",
    "Client",
)
