name: Run tox tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.6.14"
          python-version: 3.12.9

      - name: Cache tox environments
        uses: actions/cache@v4
        with:
          path: .tox/
          key: ${{ runner.os }}-tox-uv-${{ hashFiles('**/pyproject.toml', '**/tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-uv-

      - name: Install tox with UV
        run: uv pip install tox

      - name: Create test env
        shell: bash
        run: |
          cp sample.env .env
          sed -i "s|LLMWHISPERER_API_KEY=|LLMWHISPERER_API_KEY=${{ secrets.LLMWHISPERER_API_KEY }}|" .env

      - name: Run tox
        id: tox
        run: |
          tox
      - name: Render the report to the PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: llmw-py-client-test-report
          recreate: true
          path: llmw-py-client-report.md

      - name: Output reports to the job summary when tests fail
        shell: bash
        run: |
          if [ -f "llmw-py-client-report.md" ]; then
            {
              echo "<details><summary>Worker Test Report</summary>"
              echo ""
              cat "llmw-py-client-report.md"
              echo ""
              echo "</details>"
            } >> "$GITHUB_STEP_SUMMARY"
          fi
